### ISSUE TITLE
Punto 3. Proceso de configuración de los clientes

### ISSUE THREAD

**Issue by manuelalcocer** [josedom24/serviciosgs_doc#1]
Duración de la conseción (BOUND) <<-- concesión

**Comment by adrian731** [comment]
Práctica: Servidor dhcp

**Servidor dhcp**
Instala un servidor dhcp en el ordenador “servidor” que de servicio a los ordenadores de red local, teniendo en cuanta <<-- cuenta

**Uso de varios ámbitos**
Configura el servidor dhcp en el ordenador “servidor” para que de servicio a los ordenadores de la nueva red local, teniendo en cuante <-- cuenta

**Comment by josedom24** [comment]
Ok, arreglado. Gracias
