### ISSUE TITLE
Práctica: Servidor DHCP

### ISSUE THREAD

**Issue by adrian731** [josedom24/serviciosgs_doc#2]
**Servidor dhcp**
Instala un servidor dhcp en el ordenador “servidor” que de servicio a los ordenadores de red local, teniendo en _cuanta_ <<-- cuenta

**Uso de varios ámbitos**
Configura el servidor dhcp en el ordenador “servidor” para que de servicio a los ordenadores de la nueva red local, teniendo en _cuante_ <-- cuenta

**Comment by josedom24** [comment]
Ok, arreglado. Gracias.
